### ISSUE TITLE
Awesome module !

### ISSUE THREAD

**Issue by rbecheras** [node-toolkit/toolkit-tree#2]
This module is really great!

One of the keys that will help me to understand generate and base in deep!

Really great!

**Comment by rbecheras** [comment]
Ok, it's just a comment, you may close it now :-/

**Comment by rbecheras** [comment]
However, I think it would be great to add the toolkit tree in the generated docs of each toolkit component.

In particular for the main projects: `generate, base, verb, update, assemble, composer, enquirer`

![capture d ecran de 2018-01-23 11-04-52](https://user-images.githubusercontent.com/6469390/35269799-5f21fb58-002d-11e8-9328-4afd99f3ca71.png)


It's incredibly useful to understand how the things work together.

**Comment by jonschlinkert** [comment]
thanks! Means a lot to me!

> It's incredibly useful to understand how the things work together.

Great to hear! I was hoping it would be! thank you so much for the awesome compliments! you made my week!
